use std::fs::File;
use std::io::{self, Write};
use std::path::Path;
use std::result;

pub fn pixels_to_2bpp(pixels: &[u8; 64]) -> [u8; 16] {
    let mut result_bytes = [0u8; 16];

    for row in 0..8 {
        let mut low_bytes = 0u8;
        let mut high_bytes = 0u8;

        for col in 0..8 {
            let shade = pixels[row * 8 + col] & 0x03; // stay in 0..=3
            let lsb = shade & 0x01; // get bit 0 (the low bit)
            let msb = (shade >> 1) & 0x01; // get bit 1 (the high bit)

            let bit_pos = 7 - col;
            low_bytes |= lsb << bit_pos;
            high_bytes |= msb << bit_pos;
        }

        result_bytes[row * 2] = low_bytes;
        result_bytes[row * 2 + 1] = high_bytes;
    }

    result_bytes
}

pub fn export_to_bin<P: AsRef<Path>>(tiles: &[[u8; 64]], modified: &[bool], path: P) -> io::Result<()> {
    let mut file = File::create(path)?;
    for (tile, &used) in tiles.iter().zip(modified) {
        if used {
            file.write_all(&pixels_to_2bpp(tile))?;
        }
    }
    Ok(())
}

pub fn export_to_c<P: AsRef<Path>>(tiles: &[[u8; 64]], modified: &[bool], name: &str, path: P) -> io::Result<()> {
    let mut all_bytes = Vec::with_capacity(tiles.len() * 16);
    for (tile, &used) in tiles.iter().zip(modified) {
        if used {
            all_bytes.extend_from_slice(&pixels_to_2bpp(tile));
        }
    }

    let hex: Vec<String> = all_bytes.iter().map(|b| format!("0x{:02X}", b)).collect();
    let content = format!(
        "/*\n\n Tile Source File.\n\n This file was generated by DMGTile v{}\n\n https://github.com/wirenux/DMGTile\n\n*/\n\nunsigned char {}[] = {{\n      {}\n}};\n", // Insert real version (from Cargo.toml)
        env!("CARGO_PKG_VERSION"),
        name,
        hex.join(", ")
    );

    let mut file = File::create(path)?;
    file.write_all(content.as_bytes())
}

pub fn sanitize_c_ident(name: &str) -> String {
    let mut result = String::new();

    for c in name.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            result.push(c);
        } else {
            result.push('_');
        }
    }

    if result.is_empty() || result.chars().next().map_or(true, |c| c.is_ascii_digit()) {
        result.insert(0, '_');
    }

    result
}
